version: "3.8"

services:
  app:
    build:
      context: ..                # Dockerfile 있는 폴더(지금 compose가 deploy/에 있으니 상위)
      dockerfile: Dockerfile
    image: youthjob:latest       # 빌드 후 이 이름으로 태깅
    container_name: youthjob
    ports:
      - "8080:8080"
    networks: [monnet]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks: [monnet]
    depends_on: [app]

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks: [monnet]
    depends_on: [prometheus]

networks:
  monnet:
    driver: bridge
